In [33]:
!pip install xgboost
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [34]:
df=pd.read_csv('adult.csv')
df.head()

age workclass  fnlwgt  ... hours.per.week  native.country income
0   90         ?   77053  ...             40   United-States  <=50K
1   82   Private  132870  ...             18   United-States  <=50K
2   66         ?  186061  ...             40   United-States  <=50K
3   54   Private  140359  ...             40   United-States  <=50K
4   41   Private  264663  ...             40   United-States  <=50K

[5 rows x 15 columns]

In [35]:
df.shape

(32561, 15)

In [36]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

SO THIS IS A CLASSIFICATION PROBLEM STATEMENT. SO WE HAVE TO CONVERT TARGET NUMERICAL VARIABLE TO CATEGORICAL VARIABLE

EDA

In [37]:
df.income.unique()

array(['<=50K', '>50K'], dtype=object)

In [38]:
#converting target numerical value to categorical value
g={'<=50K' : 0, '>50K' : 1 }
df['income']=df['income'].map(g)
df.head()

age workclass  fnlwgt  ... hours.per.week  native.country income
0   90         ?   77053  ...             40   United-States      0
1   82   Private  132870  ...             18   United-States      0
2   66         ?  186061  ...             40   United-States      0
3   54   Private  140359  ...             40   United-States      0
4   41   Private  264663  ...             40   United-States      0

[5 rows x 15 columns]

HANDLING MISSING VALUES

In [39]:
df=df.replace('?', np.NaN)
df.head()

age workclass  fnlwgt  ... hours.per.week  native.country income
0   90       NaN   77053  ...             40   United-States      0
1   82   Private  132870  ...             18   United-States      0
2   66       NaN  186061  ...             40   United-States      0
3   54   Private  140359  ...             40   United-States      0
4   41   Private  264663  ...             40   United-States      0

[5 rows x 15 columns]

In [40]:
df.isnull().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education.num        0
marital.status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital.gain         0
capital.loss         0
hours.per.week       0
native.country     583
income               0
dtype: int64

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   workclass       30725 non-null  object
 2   fnlwgt          32561 non-null  int64 
 3   education       32561 non-null  object
 4   education.num   32561 non-null  int64 
 5   marital.status  32561 non-null  object
 6   occupation      30718 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital.gain    32561 non-null  int64 
 11  capital.loss    32561 non-null  int64 
 12  hours.per.week  32561 non-null  int64 
 13  native.country  31978 non-null  object
 14  income          32561 non-null  int64 
dtypes: int64(7), object(8)
memory usage: 3.7+ MB


In [42]:
df.workclass.unique()

array([nan, 'Private', 'State-gov', 'Federal-gov', 'Self-emp-not-inc',
       'Self-emp-inc', 'Local-gov', 'Without-pay', 'Never-worked'],
      dtype=object)

In [43]:
df.occupation.unique()

array([nan, 'Exec-managerial', 'Machine-op-inspct', 'Prof-specialty',
       'Other-service', 'Adm-clerical', 'Craft-repair',
       'Transport-moving', 'Handlers-cleaners', 'Sales',
       'Farming-fishing', 'Tech-support', 'Protective-serv',
       'Armed-Forces', 'Priv-house-serv'], dtype=object)

In [44]:
df['native.country'].unique()

array(['United-States', nan, 'Mexico', 'Greece', 'Vietnam', 'China',
       'Taiwan', 'India', 'Philippines', 'Trinadad&Tobago', 'Canada',
       'South', 'Holand-Netherlands', 'Puerto-Rico', 'Poland', 'Iran',
       'England', 'Germany', 'Italy', 'Japan', 'Hong', 'Honduras', 'Cuba',
       'Ireland', 'Cambodia', 'Peru', 'Nicaragua', 'Dominican-Republic',
       'Haiti', 'El-Salvador', 'Hungary', 'Columbia', 'Guatemala',
       'Jamaica', 'Ecuador', 'France', 'Yugoslavia', 'Scotland',
       'Portugal', 'Laos', 'Thailand', 'Outlying-US(Guam-USVI-etc)'],
      dtype=object)

In [45]:
df.workclass.value_counts()

Private             22696
Self-emp-not-inc     2541
Local-gov            2093
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: workclass, dtype: int64

In [46]:
df.occupation.value_counts()

Prof-specialty       4140
Craft-repair         4099
Exec-managerial      4066
Adm-clerical         3770
Sales                3650
Other-service        3295
Machine-op-inspct    2002
Transport-moving     1597
Handlers-cleaners    1370
Farming-fishing       994
Tech-support          928
Protective-serv       649
Priv-house-serv       149
Armed-Forces            9
Name: occupation, dtype: int64

In [47]:
df['native.country'].value_counts()

United-States                 29170
Mexico                          643
Philippines                     198
Germany                         137
Canada                          121
Puerto-Rico                     114
El-Salvador                     106
India                           100
Cuba                             95
England                          90
Jamaica                          81
South                            80
China                            75
Italy                            73
Dominican-Republic               70
Vietnam                          67
Guatemala                        64
Japan                            62
Poland                           60
Columbia                         59
Taiwan                           51
Haiti                            44
Iran                             43
Portugal                         37
Nicaragua                        34
Peru                             31
Greece                           29
France                      

In [48]:
df['workclass']=df['workclass'].fillna('Private')
df['occupation']=df['occupation'].fillna('Other')
df['native.country']=df['native.country'].fillna('United-States')
df.head()

age workclass  fnlwgt  ... hours.per.week  native.country income
0   90   Private   77053  ...             40   United-States      0
1   82   Private  132870  ...             18   United-States      0
2   66   Private  186061  ...             40   United-States      0
3   54   Private  140359  ...             40   United-States      0
4   41   Private  264663  ...             40   United-States      0

[5 rows x 15 columns]

In [49]:
df.education.value_counts()

HS-grad         10501
Some-college     7291
Bachelors        5355
Masters          1723
Assoc-voc        1382
11th             1175
Assoc-acdm       1067
10th              933
7th-8th           646
Prof-school       576
9th               514
12th              433
Doctorate         413
5th-6th           333
1st-4th           168
Preschool          51
Name: education, dtype: int64

FEATURE ENGINEERING

In [50]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education.num',
       'marital.status', 'occupation', 'relationship', 'race', 'sex',
       'capital.gain', 'capital.loss', 'hours.per.week', 'native.country',
       'income'],
      dtype='object')

In [51]:
col = ['workclass', 'education', 'marital.status', 'occupation', 'relationship', 'race', 'sex', 'native.country']

In [52]:
df['native.country'].value_counts().to_dict()

{'Cambodia': 19,
 'Canada': 121,
 'China': 75,
 'Columbia': 59,
 'Cuba': 95,
 'Dominican-Republic': 70,
 'Ecuador': 28,
 'El-Salvador': 106,
 'England': 90,
 'France': 29,
 'Germany': 137,
 'Greece': 29,
 'Guatemala': 64,
 'Haiti': 44,
 'Holand-Netherlands': 1,
 'Honduras': 13,
 'Hong': 20,
 'Hungary': 13,
 'India': 100,
 'Iran': 43,
 'Ireland': 24,
 'Italy': 73,
 'Jamaica': 81,
 'Japan': 62,
 'Laos': 18,
 'Mexico': 643,
 'Nicaragua': 34,
 'Outlying-US(Guam-USVI-etc)': 14,
 'Peru': 31,
 'Philippines': 198,
 'Poland': 60,
 'Portugal': 37,
 'Puerto-Rico': 114,
 'Scotland': 12,
 'South': 80,
 'Taiwan': 51,
 'Thailand': 18,
 'Trinadad&Tobago': 19,
 'United-States': 29753,
 'Vietnam': 67,
 'Yugoslavia': 16}

In [53]:
for feature in col:
    labels_ordered=df[feature].value_counts().to_dict()
    labels_ordered={k:i for i,k in enumerate(labels_ordered,0)}
    df[feature]=df[feature].map(labels_ordered)
df.head()

age  workclass  fnlwgt  ...  hours.per.week  native.country  income
0   90          0   77053  ...              40               0       0
1   82          0  132870  ...              18               0       0
2   66          0  186061  ...              40               0       0
3   54          0  140359  ...              40               0       0
4   41          0  264663  ...              40               0       0

[5 rows x 15 columns]

In [54]:
x = df.drop(['income'], axis=1)
y = df.income

TRAIN TEST SPLIT

In [55]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test = train_test_split(x,y, test_size =0.20, random_state = 3)

MODEL CREATION - XGBOOST CLASSIFIER

In [56]:
import xgboost

In [57]:
params={'learning_rate': [0.05, 0.10, 0.15, 0.20, 0.25, 0.30],
        'max_depth' : [3, 4, 5, 6, 8, 10, 12, 15, 20, 25, 30],
         'min_child_weight' : [1, 3, 5, 7],
        'gamma' : [0.0, 0.1, 0.2, 0.3, 0.4], 
        'colsample_bytree' : [0.3, 0.4, 0.5, 0.7]}

In [58]:
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
clf=xgboost.XGBClassifier()
random_search=RandomizedSearchCV(clf, param_distributions=params, n_iter=5, scoring='roc_auc', n_jobs=-1, cv=5, verbose=3)
random_search.fit(x_train, y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 out of  25 | elapsed:   32.2s finished


RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=XGBClassifier(base_score=0.5, booster='gbtree',
                                           colsample_bylevel=1,
                                           colsample_bynode=1,
                                           colsample_bytree=1, gamma=0,
                                           learning_rate=0.1, max_delta_step=0,
                                           max_depth=3, min_child_weight=1,
                                           missing=None, n_estimators=100,
                                           n_jobs=1, nthread=None,
                                           objective='binary:logistic',
                                           random_state=0, reg_alpha=0,
                                           reg_lambda=1, sc...
                                           verbosity=1),
                   iid='deprecated', n_iter=5, n_jobs=-1,
                   param_distributions={'colsample_bytree': [0

In [59]:
random_search.best_estimator_

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.4, gamma=0.4,
              learning_rate=0.3, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [60]:
random_search.best_params_

{'colsample_bytree': 0.4,
 'gamma': 0.4,
 'learning_rate': 0.3,
 'max_depth': 6,
 'min_child_weight': 1}

In [61]:
clf=xgboost.XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.4, gamma=0.2,
              learning_rate=0.25, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [62]:
from sklearn.model_selection import cross_val_score
score=cross_val_score(clf, x_train, y_train, cv=10)

In [63]:
score

array([0.86986564, 0.8706334 , 0.87754319, 0.87024952, 0.86641075,
       0.86487524, 0.88253359, 0.87024952, 0.87442396, 0.86866359])

In [65]:
score.mean()

0.8715448402133438

In [64]:
clf.fit(x_train, y_train)
y_pred=clf.predict(x_test)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

from sklearn.metrics import accuracy_score
print('accuracy is',accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.90      0.94      0.92      4930
           1       0.80      0.67      0.73      1583

    accuracy                           0.88      6513
   macro avg       0.85      0.81      0.82      6513
weighted avg       0.87      0.88      0.87      6513

[[4656  274]
 [ 520 1063]]
accuracy is 0.8780899738983571
